In [2]:
import pandas as pd
import sqlite3
import os
conn=sqlite3.connect("../../db/proyectomacro.db")
df=pd.read_sql_query("SELECT * FROM PIB_real_Gasto", conn, index_col="año")
componentes = [
    'gastos_consumo',
    'formacion_capital',
    'exportacion_bienes_servicios',
    'importacion_bienes',
    'consumo_privado',
    'consumo_publico'
]
pct = df[componentes].div(df["pib_real_base_1990"], axis=0) * 100
pct

,gastos_consumo,formacion_capital,exportacion_bienes_servicios,importacion_bienes,consumo_privado,consumo_publico
año,,,,,,
1950,87.391301,11.956526,16.304355,15.652181,78.913045,8.478255
1951,82.914575,16.080395,18.592961,17.587948,75.753772,7.160803
1952,85.009305,16.387334,17.225331,18.621971,79.050275,5.959031
1953,91.840397,10.214413,5.866588,7.921380,88.237050,3.603329
1954,87.559012,13.369886,4.355116,5.283997,84.680982,2.878031
...,...,...,...,...,...,...
2019,83.098771,22.777324,24.770286,30.646380,71.055703,12.043068
2020,84.574050,18.584554,22.039274,25.197878,71.742560,12.831489
2021,83.963833,19.537612,23.974363,27.475809,71.219028,12.744804
2022,84.498023,18.881002,26.777112,28.564968,71.690697,12.807326
2023,84.581569,19.182159,23.789470,27.553197,NaN,NaN

In [5]:
# 1) Con DataFrame.eval (muy legible):
pct['CIGX_minus_M'] = pct.eval(
    'gastos_consumo + formacion_capital + exportacion_bienes_servicios - importacion_bienes'
)
pct.head(30)

,gastos_consumo,formacion_capital,exportacion_bienes_servicios,importacion_bienes,consumo_privado,consumo_publico,CIGX_minus_M
año,,,,,,,
1950,87.391301,11.956526,16.304355,15.652181,78.913045,8.478255,100.000000
1951,82.914575,16.080395,18.592961,17.587948,75.753772,7.160803,99.999983
1952,85.009305,16.387334,17.225331,18.621971,79.050275,5.959031,100.000000
1953,91.840397,10.214413,5.866588,7.921380,88.237050,3.603329,100.000018
1954,87.559012,13.369886,4.355116,5.283997,84.680982,2.878031,100.000017
1955,80.166363,20.848892,4.807747,5.823019,78.004838,2.161525,99.999983
1956,82.753907,19.871618,13.358333,15.983841,79.122188,3.631701,100.000018
1957,89.397216,18.867412,22.519938,30.784566,81.017696,8.379502,100.000000
1958,92.621241,16.810475,15.977390,25.409106,83.397792,9.223449,100.000000
1959,94.432940,12.351112,20.352155,27.136207,85.059561,9.373379,100.000000
1960,92.554877,15.274949,16.429055,24.258881,83.797245,8.757632,100.000000
1961,95.730709,11.206895,16.399834,23.337438,86.494261,9.236448,100.000000
1962,92.040550,16.444535,16.444535,24.929604,82.804574,9.235960,100.000016
1963,93.305434,15.847281,17.346584,26.499299,83.664572,9.640861,100.000000
1964,87.204074,15.611939,20.686992,23.503019,77.703841,9.500232,99.999986
1965,88.189411,16.963790,21.448467,26.601669,76.671304,11.518108,100.000000
1966,88.100627,16.238989,21.924535,26.264150,76.477985,11.622642,100.000000
1967,89.230428,14.300038,22.441249,25.971715,78.349483,10.880945,100.000000
1968,86.244121,18.014125,19.721354,23.979588,75.667196,10.576925,100.000011
1969,88.802606,15.477695,19.306488,23.586778,78.074769,10.727826,100.000011
1970,83.096201,17.065479,20.161684,20.323363,72.392882,10.703319,100.000000
1971,85.608800,17.174921,17.248760,20.032491,74.385291,11.223509,99.999990
1972,82.880171,19.827234,17.177808,19.885213,71.749086,11.131084,100.000000
1973,80.192663,20.713081,22.559107,23.464843,69.392851,10.799812,100.000009
1974,77.066362,16.406233,28.731680,22.204266,66.769766,10.296595,100.000008
1975,81.183313,24.442592,21.288186,26.914091,69.600216,11.583097,100.000000
1976,81.060112,21.168529,22.495437,24.724078,69.190565,11.869539,100.000000
1977,82.028521,20.795770,22.250847,25.075131,68.905246,13.123275,100.000007
1978,86.672592,20.004183,18.615480,25.292256,72.574995,14.097604,100.000000
1979,88.282131,17.615366,19.329538,25.227035,74.946773,13.335358,100.000000